// Generated by CoffeeScript 1.10.0
(function() {
  var app, bodyParser, branchUrl, express, getTime, pipelineUrl, port, request, slackUrl;

  express = require('express');

  bodyParser = require('body-parser');

  request = require('request');

  port = process.env['PORT'] || 5000;

  slackUrl = process.env['SLACK_URL'];

  app = express();

  app.use(bodyParser.json());

  pipelineUrl = function(body) {
    return "https://gitlab.com/" + body.project.path_with_namespace + "/pipelines/" + body.object_attributes.id;
  };

  branchUrl = function(body) {
    return "https://gitlab.com/" + body.project.path_with_namespace + "/commits/" + body.object_attributes.ref;
  };

  getTime = function(body) {
    var diff, min, sec;
    diff = Date.parse(body.object_attributes.finished_at) - Date.parse(body.object_attributes.created_at);
    min = Math.floor((diff / 1000) / 60);
    sec = Math.floor((diff / 1000) % 60);
    return min + ":" + sec;
  };

  app.post('/', function(req, res) {
    var authorName, authorUsername, body, branch, color, data, pipeline, pretext, projectName, projectUrl, status, success, text, title, value;
    body = req.body;
    pipeline = body.object_attributes.id;
    projectName = body.project.path_with_namespace;
    projectUrl = body.project.web_url;
    branch = body.object_attributes.ref;
    authorName = "" + body.user.name;
    authorUsername = "" + body.user.username;
    success = body.object_attributes.status === "success" ? true : false;
    status = success ? "passed" : "failed";
    pretext = "<" + projectUrl + "|" + projectName + ">: Gitlab CI pipeline <#" + pipeline + "|" + (pipelineUrl(body)) + "> of branch <" + branch + "|" + (branchUrl(body)) + "> " + status + ".";
    text = "by " + authorName + " (" + authorUsername + ")";
    title = "<" + branch + "|" + (branchUrl(body)) + ">";
    value = "in " + (getTime(body));
    color = success ? "#36a64f" : "#ff2e2a";
    data = {
      attachments: [
        {
          color: color,
          pretext: pretext,
          text: text,
          fields: {
            title: title,
            value: value
          }
        }
      ],
      username: "Gitlab CI - " + body.project.name
    };
    console.log(JSON.stringify(data));
    request.post({
      url: slackUrl,
      body: data,
      json: true
    });
    return res.send('ok');
  });

  app.listen(port);

}).call(this);
